### ISSUE TITLE
Crash en cas de mauvaise clé RSA

### ISSUE THREAD

**Issue by Alekshar** [Alekshar/TamagochIoT#1]
![tap](https://cloud.githubusercontent.com/assets/6387602/23268784/fcde1aac-f9ee-11e6-9348-219da23803ef.jpg)

@B3ND3L : il semble qu'il manque un try/catch au décryptage du serveur central

**Comment by B3ND3L** [comment]
Comment je peux reproduire le crash ?

**Comment by Alekshar** [comment]
D'après son découvreur @Nolyurn : en utilisant la mauvaise clé publique pour crypter le message

**Comment by B3ND3L** [comment]
Ok, je vais corriger ça

**Comment by B3ND3L** [comment]
Problème corrigé
